version: "3.8"

services:

  core:
    depends_on:
      - mysql
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/traveather_database",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2

  rabbitmq:
    image: rabbitmq:3.12.9-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
